// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPumgRmzSWMN3fHrkUhfbPTgnp-o7NzL8',
    appId: '1:514215480812:web:daf751112ca2e2f89244c9',
    messagingSenderId: '514215480812',
    projectId: 'crud9-31e3b',
    authDomain: 'crud9-31e3b.firebaseapp.com',
    storageBucket: 'crud9-31e3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6uNutqgb4vEKMM2_gopTAyYEUNl1Kf50',
    appId: '1:514215480812:android:bc8d2b0bca0f8fd09244c9',
    messagingSenderId: '514215480812',
    projectId: 'crud9-31e3b',
    storageBucket: 'crud9-31e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHwnhBFh3ziObhHSt0RUKvTXlVX7SoE0',
    appId: '1:514215480812:ios:0748ab48d50cb4369244c9',
    messagingSenderId: '514215480812',
    projectId: 'crud9-31e3b',
    storageBucket: 'crud9-31e3b.appspot.com',
    iosBundleId: 'com.example.userCrud9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHwnhBFh3ziObhHSt0RUKvTXlVX7SoE0',
    appId: '1:514215480812:ios:0748ab48d50cb4369244c9',
    messagingSenderId: '514215480812',
    projectId: 'crud9-31e3b',
    storageBucket: 'crud9-31e3b.appspot.com',
    iosBundleId: 'com.example.userCrud9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPumgRmzSWMN3fHrkUhfbPTgnp-o7NzL8',
    appId: '1:514215480812:web:bdbb61b09cdb47239244c9',
    messagingSenderId: '514215480812',
    projectId: 'crud9-31e3b',
    authDomain: 'crud9-31e3b.firebaseapp.com',
    storageBucket: 'crud9-31e3b.appspot.com',
  );
}
